"""rename epochs to iters on training_runs

Revision ID: ef840716d6de
Revises: 04d1b7ab7806
Create Date: 2026-07-01 22:35:05.530476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef840716d6de'
down_revision: Union[str, Sequence[str], None] = '04d1b7ab7806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_runs', sa.Column('iters', sa.Integer(), nullable=False))
    op.drop_column('training_runs', 'epochs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_runs', sa.Column('epochs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('training_runs', 'iters')
    # ### end Alembic commands ###
